---
_extends: .github:common-settings.yaml

repository:
  name: tokentoilet
  description: Chump and dump
  topics: next-js, react

branches:
  - name: main
    protection:
      enforce_admins: true
      required_linear_history: true
      required_pull_request_reviews: null
      required_status_checks:
        strict: false
        contexts: ['Lint']
      restrictions: null
