---
name: Setup Project
description: Setup Node.js, pnpm, and install dependencies

inputs:
  node-version:
    description: Node.js version to setup
    required: false
    default: '22'
  install-dependencies:
    description: Whether to install dependencies
    required: false
    default: 'true'
  cache-key-suffix:
    description: Additional suffix for cache keys
    required: false
    default: ''

outputs:
  node-version:
    description: The Node.js version that was setup
    value: ${{ steps.setup-node.outputs.node-version }}
  cache-hit:
    description: Whether pnpm cache was hit
    value: ${{ steps.setup-pnpm.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Setup pnpm
      id: setup-pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      with:
        run_install: false

    - name: Setup Node.js
      id: setup-node
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
      with:
        node-version: ${{ inputs.node-version }}
        package-manager-cache: false

    - id: cache-config
      name: Configure cache
      run: |
        pnpm_store_path="$(pnpm store path --silent)"
        if [ -z "pnpm_store_path" ]; then
          echo "Failed to get pnpm store path"
          exit 1
        fi
        mkdir -p "pnpm_store_path" || exit 1
        echo "path=$pnpm_store_path" >> $GITHUB_OUTPUT
        year_month=$(date -u '+%Y%m')
        base_key="${{ runner.os }}-pnpm-cache-v${year_month}${{ inputs.cache-key-suffix && '-' }}${{ inputs.cache-key-suffix }}"
        echo "key=${base_key}-${{ hashFiles('**/pnpm-lock.yaml') }}" >> $GITHUB_OUTPUT
        echo "restore-keys=${base_key}-" >> $GITHUB_OUTPUT
        echo "nextjs-key=${{ runner.os }}-nextjs-cache${{ inputs.cache-key-suffix && '-' }}${{ inputs.cache-key-suffix }}-${{ hashFiles('**/pnpm-lock.yaml') }}" >> $GITHUB_OUTPUT
      shell: 'bash -Eeuo pipefail {0}'

    - name: Setup pnpm cache
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        key: ${{ steps.cache-config.outputs.key }}
        path: ${{ steps.cache-config.outputs.path }}
        restore-keys: ${{ steps.cache-config.outputs.restore-keys }}

    - name: Install dependencies
      if: inputs.install-dependencies == 'true'
      shell: bash
      run: pnpm install --prefer-offline --loglevel warn

    - name: Verify installation
      if: inputs.install-dependencies == 'true'
      shell: bash
      run: |
        echo "Node.js version: $(node --version)"
        echo "pnpm version: $(pnpm --version)"
        echo "Dependencies installed successfully"

    - id: cache-nextjs
      name: Setup Next.js related caches
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
      with:
        key: ${{ steps.cache-config.outputs.nextjs-key }}
        path: |
          .next/cache
          .cache
          **/tsconfig.tsbuildinfo
