onlyBuiltDependencies:
  - '@reown/appkit'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver

overrides:
  '@metamask/sdk-communication-layer@>=0.16.0 <=0.33.0': '>=0.33.1'
  '@metamask/sdk@>=0.16.0 <=0.33.0': '>=0.33.1'
  jiti: <2.2.0

shamefullyHoist: true
