---
# Renovate this repository if Renovate-specific tasks are checked, if this workflow file or the Renovate configuration file is changed, or if dispatched.
name: Renovate

on:
  issues:
    types: [edited]
  pull_request:
    types: [edited]
  push:
    branches-ignore: [main]
  workflow_dispatch:
    inputs:
      log-level:
        description: Log level for Renovate
        required: false
        type: string
        default: debug
      print-config:
        description: Log the fully-resolved Renovate config for each repository, plus fully-resolved presets.
        required: false
        type: boolean
        default: false
  workflow_run:
    branches: [main]
    types: [completed]
    workflows: [CI]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  renovate:
    if: github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success'
    name: Renovate
    secrets:
      APPLICATION_ID: ${{ secrets.APPLICATION_ID }}
      APPLICATION_PRIVATE_KEY: ${{ secrets.APPLICATION_PRIVATE_KEY }}
    uses: bfra-me/.github/.github/workflows/renovate.yaml@6f4321b4d329ecf1268c3ad8875b820fe1283180 # v2.4.0
    with:
      log_level: ${{ inputs.log-level || (github.event_name == 'pull_request' || github.ref_name != github.event.repository.default_branch) && 'debug' || 'info' }}
      print_config: ${{ inputs.print-config || false }}
